[workspace]

[package]
name = "triton"
version = "0.1.0"
edition = "2021"

[dependencies]

triton-vm = "0.29.1"
triton-opcodes = "0.29.1"
twenty-first = "0.28"
zero-knowledge = { path = "../zero-knowledge" }
