[workspace]

[package]
name = "triton"
version = "0.1.0"
edition = "2021"

[dependencies]

triton-vm = "0.20"
triton-opcodes = "0.20"
twenty-first = "0.19.3"
zero-knowledge = { path = "../zero-knowledge" }
